// 2026-05-11 [opus-4-7] Phase 6: 絵文字データを抽出（元 CrafticaEditor.tsx L289-311）
import type { EmojiEntry } from '../types';
export type { EmojiEntry };

export const EMOJIS: EmojiEntry[] = [
  // 顔・感情
  {e:'😀',k:'grinning smile happy 笑顔 嬉しい'},{e:'😁',k:'grin beaming smile 歯 笑'},{e:'😂',k:'joy laugh cry tears 笑い泣き'},{e:'🤣',k:'rofl rolling floor laugh 爆笑'},{e:'😊',k:'smile blush 微笑み'},{e:'😇',k:'innocent halo angel 天使'},{e:'🥰',k:'hearts love 愛 ハート 幸せ'},{e:'😍',k:'heart eyes love 目がハート'},{e:'🤩',k:'star struck excited キラキラ 興奮'},{e:'😘',k:'kiss wink キス'},{e:'😋',k:'yum delicious おいしい'},{e:'😎',k:'cool sunglasses クール サングラス'},{e:'🤗',k:'hugging hug ハグ'},{e:'🤔',k:'thinking hmm 考え中'},{e:'🤫',k:'shushing secret しー 内緒'},{e:'🤭',k:'giggle laugh 口に手'},{e:'😐',k:'neutral 無表情'},{e:'😏',k:'smirk ニヤリ 含み笑い'},{e:'😒',k:'unamused 不満 つまらない'},{e:'🙄',k:'eye roll あきれる'},{e:'😔',k:'pensive sad 落ち込む'},{e:'😴',k:'sleeping sleep 寝る ZZZ'},{e:'😷',k:'mask sick 病気 マスク'},{e:'🤒',k:'thermometer fever 熱 病気'},{e:'🤕',k:'bandage hurt けが'},{e:'🤢',k:'nauseated 吐き気 気持ち悪い'},{e:'🤮',k:'vomit 嘔吐'},{e:'🥵',k:'hot heat 暑い'},{e:'🥶',k:'cold freeze 寒い'},{e:'🤯',k:'exploding head 衝撃 びっくり'},{e:'🥳',k:'party celebrate パーティー 祝い'},{e:'😢',k:'crying tear 泣き'},{e:'😭',k:'sob loud cry 大泣き'},{e:'😱',k:'scream fear 叫び 恐怖'},{e:'😡',k:'angry 怒り'},{e:'🤬',k:'cursing 激怒'},{e:'😈',k:'devil evil 悪魔'},{e:'💀',k:'skull death 骸骨 死'},{e:'💩',k:'poop ウンコ'},{e:'🤖',k:'robot ロボット AI'},{e:'👻',k:'ghost おばけ'},{e:'👽',k:'alien 宇宙人'},{e:'🤡',k:'clown ピエロ'},
  // ジェスチャー・手
  {e:'👋',k:'wave hello bye 手を振る'},{e:'✋',k:'raised hand stop ストップ'},{e:'👌',k:'ok okay 了解 OK'},{e:'✌️',k:'victory peace ピース'},{e:'🤞',k:'crossed fingers luck 幸運'},{e:'🤟',k:'love you 愛してる'},{e:'🤘',k:'rock ロック'},{e:'👍',k:'thumbs up good いいね'},{e:'👎',k:'thumbs down bad ダメ'},{e:'👏',k:'clapping applause 拍手'},{e:'🙌',k:'raising hands 万歳'},{e:'🙏',k:'pray thank please お願い ありがとう 合掌'},{e:'💪',k:'muscle flex strong 力こぶ'},{e:'👀',k:'eyes look see 目'},{e:'👅',k:'tongue 舌'},{e:'🧠',k:'brain smart 脳 頭脳'},
  // ハート
  {e:'❤️',k:'red heart love 赤ハート 愛'},{e:'🧡',k:'orange heart オレンジ'},{e:'💛',k:'yellow heart 黄色'},{e:'💚',k:'green heart 緑'},{e:'💙',k:'blue heart 青'},{e:'💜',k:'purple heart 紫'},{e:'🖤',k:'black heart 黒'},{e:'🤍',k:'white heart 白'},{e:'💔',k:'broken heart 失恋'},{e:'💕',k:'two hearts ラブラブ'},{e:'💖',k:'sparkling heart キラキラ'},{e:'💗',k:'growing heart'},{e:'💘',k:'heart arrow キューピッド'},{e:'💝',k:'heart ribbon プレゼント'},
  // 動物
  {e:'🐶',k:'dog puppy 犬 わんわん'},{e:'🐱',k:'cat kitten 猫 にゃー'},{e:'🐭',k:'mouse ネズミ'},{e:'🐹',k:'hamster ハムスター'},{e:'🐰',k:'rabbit bunny ウサギ'},{e:'🦊',k:'fox キツネ'},{e:'🐻',k:'bear クマ'},{e:'🐼',k:'panda パンダ'},{e:'🐨',k:'koala コアラ'},{e:'🐯',k:'tiger トラ'},{e:'🦁',k:'lion ライオン'},{e:'🐮',k:'cow ウシ'},{e:'🐷',k:'pig ブタ'},{e:'🐸',k:'frog カエル'},{e:'🐵',k:'monkey サル'},{e:'🐔',k:'chicken ニワトリ'},{e:'🐧',k:'penguin ペンギン'},{e:'🦆',k:'duck アヒル'},{e:'🦋',k:'butterfly チョウ'},{e:'🐝',k:'bee honeybee ハチ'},{e:'🐞',k:'ladybug テントウムシ'},{e:'🦀',k:'crab カニ'},{e:'🐙',k:'octopus タコ'},{e:'🐠',k:'fish 熱帯魚'},{e:'🐬',k:'dolphin イルカ'},{e:'🦈',k:'shark サメ'},{e:'🐢',k:'turtle カメ'},{e:'🐍',k:'snake ヘビ'},{e:'🐉',k:'dragon 竜 ドラゴン'},{e:'🦄',k:'unicorn ユニコーン'},
  // 植物・自然
  {e:'🌸',k:'cherry blossom sakura 桜'},{e:'🌺',k:'hibiscus 花'},{e:'🌻',k:'sunflower ヒマワリ'},{e:'🌹',k:'rose バラ'},{e:'🌷',k:'tulip チューリップ'},{e:'💐',k:'bouquet 花束'},{e:'🌱',k:'seedling sprout 芽'},{e:'🌿',k:'herb leaf 葉'},{e:'🍀',k:'clover luck 四つ葉 幸運'},{e:'🍁',k:'maple leaf 紅葉 もみじ'},{e:'☀️',k:'sun sunny 太陽 晴れ'},{e:'🌧️',k:'rain 雨'},{e:'⛈️',k:'thunder storm 雷雨'},{e:'❄️',k:'snowflake cold winter 雪 寒い'},{e:'⛄',k:'snowman 雪だるま'},{e:'🌈',k:'rainbow 虹'},{e:'🔥',k:'fire flame hot 炎 熱い'},{e:'💧',k:'droplet water 水'},{e:'🌊',k:'wave ocean 波 海'},{e:'🌍',k:'earth globe world 地球'},{e:'🌕',k:'full moon 満月'},{e:'🌙',k:'crescent moon 三日月'},{e:'⭐',k:'star 星'},{e:'✨',k:'sparkles きらきら'},{e:'💫',k:'dizzy star くらくら'},{e:'🌟',k:'glowing star 輝く星'},
  // 食べ物・飲み物
  {e:'🍎',k:'apple リンゴ'},{e:'🍊',k:'orange tangerine みかん'},{e:'🍋',k:'lemon レモン'},{e:'🍇',k:'grapes ブドウ'},{e:'🍓',k:'strawberry イチゴ'},{e:'🍑',k:'peach モモ 桃'},{e:'🍒',k:'cherries チェリー さくらんぼ'},{e:'🍕',k:'pizza ピザ'},{e:'🍔',k:'burger hamburger バーガー'},{e:'🍟',k:'fries フライドポテト'},{e:'🍜',k:'ramen noodle ラーメン'},{e:'🍣',k:'sushi 寿司'},{e:'🍱',k:'bento 弁当'},{e:'🍙',k:'rice ball onigiri おにぎり'},{e:'🍰',k:'cake shortcake ケーキ'},{e:'🎂',k:'birthday cake バースデー 誕生日'},{e:'🍩',k:'donut ドーナツ'},{e:'🍪',k:'cookie クッキー'},{e:'🍫',k:'chocolate チョコレート'},{e:'🍬',k:'candy キャンディ'},{e:'☕',k:'coffee コーヒー'},{e:'🍵',k:'tea お茶 緑茶'},{e:'🧋',k:'bubble tea タピオカ'},{e:'🍺',k:'beer ビール'},{e:'🍻',k:'cheers 乾杯'},{e:'🥂',k:'champagne シャンパン'},{e:'🍷',k:'wine ワイン'},
  // 乗り物・場所
  {e:'🚀',k:'rocket launch space ロケット 宇宙'},{e:'✈️',k:'airplane flight 飛行機'},{e:'🚗',k:'car auto 車 自動車'},{e:'🚌',k:'bus バス'},{e:'🚕',k:'taxi タクシー'},{e:'🚑',k:'ambulance 救急車'},{e:'🚒',k:'fire truck 消防車'},{e:'🛸',k:'ufo UFO'},{e:'⛵',k:'sailboat ヨット'},{e:'🚢',k:'ship 船'},{e:'🏠',k:'house home 家'},{e:'🏢',k:'office building ビル'},{e:'🗼',k:'tokyo tower 東京タワー'},{e:'🏯',k:'castle 城'},{e:'🌏',k:'asia earth 地球 アジア'},
  // 活動・スポーツ
  {e:'⚽',k:'soccer football サッカー'},{e:'🏀',k:'basketball バスケ'},{e:'⚾',k:'baseball 野球'},{e:'🎾',k:'tennis テニス'},{e:'🏓',k:'table tennis ping pong 卓球'},{e:'🥊',k:'boxing ボクシング'},{e:'🎮',k:'video game ゲーム コントローラー'},{e:'🎲',k:'dice サイコロ'},{e:'🎯',k:'dart target ダーツ'},{e:'🎨',k:'art palette 絵 アート'},{e:'🎬',k:'cinema movie 映画'},{e:'🎤',k:'microphone マイク 歌'},{e:'🎵',k:'music note 音楽 音符'},{e:'🎶',k:'music notes メロディ'},{e:'🎸',k:'guitar ギター'},{e:'🎹',k:'piano ピアノ'},{e:'🥁',k:'drum ドラム 太鼓'},{e:'🎺',k:'trumpet トランペット'},{e:'🎻',k:'violin バイオリン'},{e:'🏆',k:'trophy win champion トロフィー 優勝'},{e:'🥇',k:'gold medal 金メダル'},{e:'🎁',k:'gift present プレゼント'},{e:'🎉',k:'party popper 祝い パーティー'},{e:'🎊',k:'confetti お祝い'},{e:'🎈',k:'balloon 風船'},{e:'🎆',k:'fireworks 花火'},
  // オブジェクト・ツール
  {e:'📱',k:'phone mobile smartphone スマホ 携帯'},{e:'💻',k:'laptop computer パソコン PC'},{e:'🖥️',k:'desktop computer デスクトップ'},{e:'⌨️',k:'keyboard キーボード'},{e:'🖱️',k:'mouse マウス'},{e:'📷',k:'camera 写真 カメラ'},{e:'📺',k:'television TV テレビ'},{e:'🔋',k:'battery charge バッテリー 充電'},{e:'💡',k:'light bulb idea アイデア ひらめき'},{e:'📚',k:'books reading 本 読書'},{e:'📖',k:'book open 本'},{e:'📝',k:'memo note メモ ノート'},{e:'📋',k:'clipboard クリップボード'},{e:'📌',k:'pin 画鋲 ピン'},{e:'✏️',k:'pencil 鉛筆'},{e:'🔍',k:'search magnify 検索 虫眼鏡'},{e:'🔒',k:'locked 鍵 ロック'},{e:'🔑',k:'key 鍵 キー'},{e:'🔧',k:'wrench 工具 修理'},{e:'⚙️',k:'gear setting 歯車 設定'},{e:'🧲',k:'magnet 磁石'},{e:'🧪',k:'test tube lab 実験'},{e:'🔬',k:'microscope 顕微鏡'},{e:'🔭',k:'telescope 望遠鏡'},{e:'💊',k:'pill medicine 薬'},{e:'💉',k:'syringe injection 注射'},{e:'🏷️',k:'label tag タグ'},{e:'🔖',k:'bookmark しおり'},
  // 記号・シンボル
  {e:'✅',k:'check done complete 完了 OK チェック'},{e:'❌',k:'cross no wrong NG バツ 間違い'},{e:'⚠️',k:'warning caution 警告 注意'},{e:'🚫',k:'prohibited no 禁止'},{e:'♻️',k:'recycle リサイクル'},{e:'💯',k:'hundred 100点 完璧 満点'},{e:'💢',k:'anger 怒り'},{e:'💥',k:'explosion 爆発'},{e:'💦',k:'sweat water 汗 水'},{e:'💨',k:'wind 風 速い'},{e:'💬',k:'speech bubble comment 吹き出し'},{e:'💭',k:'thought 考え 思考'},{e:'🔔',k:'bell notification 通知 ベル'},{e:'📣',k:'megaphone announce アナウンス'},{e:'🔊',k:'volume speaker 大音量'},{e:'🔇',k:'mute 消音'},{e:'💤',k:'zzz sleep 睡眠 ZZZ'},{e:'❓',k:'question 疑問'},{e:'❗',k:'exclamation 感嘆'},{e:'✅',k:'check ok 完了'},{e:'🆕',k:'new 新しい NEW'},{e:'🆒',k:'cool クール'},{e:'🆓',k:'free 無料'},{e:'🔴',k:'red circle 赤丸'},{e:'🟢',k:'green circle 緑丸'},{e:'🔵',k:'blue circle 青丸'},{e:'⚫',k:'black circle 黒丸'},{e:'⚪',k:'white circle 白丸'},{e:'🇯🇵',k:'japan flag 日本 国旗'},{e:'🇺🇸',k:'usa america flag アメリカ'},
];
